name: submit-azure-machine-learning-job

variables:
  service-connection: 'Traineeship connection' # replace with your generic service connection name
  resource-group: 'MaRi-invest' # replace with your resource group name
  workspace: 'ML_Mari_invest' # replace with your workspace name
  endpoint_name: demand-forecast-1
  endpoint_type: online

trigger:
- none

jobs:
- job: SubmitAzureMLJob
  displayName: Submit AzureML Job
  timeoutInMinutes: 300
  pool:
    vmImage: ubuntu-latest
  steps:
  - checkout: self
    path: s/
  - template: /Azure-devops/templates/create-connection-workspace.yml
  

  # - template: /aml-cli-v2/create-deployment.yml
  #   parameters:
  #     deployment_name: demand-forest-dp
  #     deployment_file: mlops/azureml/deploy/online/online-deployment.yml

  # - task: AzureCLI@2
  #   displayName: Create online/batch endpoint 
  #   continueOnError: true
  #   inputs: 
  #     azureSubscription: $(service-connection) #needs to have access at the RG level 
  #     scriptType: bash
  #     scriptLocation: inlineScript
  #     inlineScript: |
  #       ENDPOINT_EXISTS=$(az ml $(endpoint_type)-endpoint list -o tsv --query "[?name=='$(endpoint_name)'][name]" | wc -l)
  #       echo $ENDPOINT_NAME $ENDPOINT_EXISTS
  #       az ml $(endpoint_type)-endpoint list -g $(resource-group) -w $(workspace) -o tsv 

  #       if [[ ENDPOINT_EXISTS -ne 1 ]]; then
  #           az ml $(endpoint_type)-endpoint create --name $(endpoint_name) -g $(resource-group) -w $(workspace)
  #       else
  #           echo "Endpoint exists"
  #       fi
